name: Trigger auto deployment for uptimekumay

# When this action will be executed
on:
  # Automatically trigger it when detected changes in repo
  push:
    branches: 
      [ master ]
    paths:
    - '**'
    - '.github/workflows/uptimekumay-AutoDeployTrigger-886d5b62-8761-4abe-9dc4-a2f36ede6357.yml'

  # Allow manual trigger 
  workflow_dispatch:      

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions: 
      id-token: write #This is required for requesting the OIDC JWT Token
      contents: read #Required when GH token is used to authenticate with private repo

    steps:
      - name: Checkout to the branch
        uses: actions/checkout@v2

      - name: Azure Login
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.UPTIMEKUMAY_AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.UPTIMEKUMAY_AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.UPTIMEKUMAY_AZURE_SUBSCRIPTION_ID }}

      - name: Log in to container registry
        uses: docker/login-action@v3
        with:
          registry: uptimekumaa.azurecr.io
          username: ${{ secrets.UPTIMEKUMAY_REGISTRY_USERNAME }}
          password: ${{ secrets.UPTIMEKUMAY_REGISTRY_PASSWORD }}

      - name: Build and push image with target
        uses: docker/build-push-action@v6
        with:
          context: ${{ github.workspace }}
          file: ./docker/dockerfile
          target: release
          push: true
          tags: uptimekumaa.azurecr.io/uptimekumay:${{ github.sha }}

      - name: Deploy to Azure Container Apps
        uses: azure/container-apps-deploy-action@v2
        with:
          containerAppName: uptimekumay
          resourceGroup: iamnew
          imageToDeploy: uptimekumaa.azurecr.io/uptimekumay:${{ github.sha }}
          registryUrl: uptimekumaa.azurecr.io
          registryUsername: ${{ secrets.UPTIMEKUMAY_REGISTRY_USERNAME }}
          registryPassword: ${{ secrets.UPTIMEKUMAY_REGISTRY_PASSWORD }}


